spring:
  jpa:
    database: h2
    properties.hibernate:
      show_sql: true
    hibernate:
      ddl-auto: validate


---
spring.config:
  activate:
    on-profile: webtoon-local-test

spring:
  jpa:
    database: h2
    properties.hibernate:
      show_sql: true
      format_sql: true
    hibernate:
      ddl-auto: create

---
spring.config:
  activate:
    on-profile: webtoon-integration-test

spring:
  jpa:
    database: h2
    properties.hibernate:
      show_sql: true
      format_sql: true
    hibernate:
      ddl-auto: create

---

spring.config:
  activate:
    on-profile: webtoon-core-local

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/webtoon
    username: root
    password: root
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate


---
spring.config:
  activate:
    on-profile: webtoon-core-beta

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/webtoon?useUnicode=true&characterEncoding=utf8
    username: ${WEBTOON_SERVICE_DB_USERNAME}
    password: ${WEBTOON_SERVICE_DB_PASSWORD}
  jpa:
    database: mysql

