create table account (
                         id bigint generated by default as identity,
                         created_at timestamp,
                         device_id varchar(255),
                         modified_at timestamp,
                         nickname varchar(255),
                         primary key (id)
);


create table author (
                        id bigint generated by default as identity,
                        created_at timestamp,
                        modified_at timestamp,
                        name varchar(255),
                        primary key (id)
);

create table review (
                        id bigint generated by default as identity,
                        comment clob,
                        created_at timestamp,
                        drawing_score double,
                        modified_at timestamp,
                        story_score double,
                        account_id bigint,
                        webtoon_id bigint,
                        primary key (id)
);

create table webtoon (
                         id bigint generated by default as identity,
                         created_at timestamp,
                         modified_at timestamp,
                         popularity integer,
                         site varchar(255),
                         summary varchar(255),
                         thumbnail varchar(255),
                         title varchar(255),
                         url varchar(255),
                         primary key (id)
);

create table webtoon_authors (
                                 webtoons_id bigint not null,
                                 authors_id bigint not null
);

create table week_day (
                          id bigint not null,
                          weekdays varchar(255)
);
alter table review
    add constraint FKbopwpfvcg5qsfrjtt9svofxg1
        foreign key (account_id)
            references account;

alter table review
    add constraint FKf2ymxtqydyuobv4cddh2sdj1h
        foreign key (webtoon_id)
            references webtoon;

alter table webtoon_authors
    add constraint FK77cyo4qejc6l1awbo4ij2c774
        foreign key (authors_id)
            references author;

alter table webtoon_authors
    add constraint FK6plp6kntlxrijcrxljwl2a04r
        foreign key (webtoons_id)
            references webtoon;

alter table week_day
    add constraint FKcplni9utxc6rhasouaxp1e4c6
        foreign key (id)
            references webtoon;
