CREATE TABLE BATCH_JOB_EXECUTION_SEQ
(
    ID         BIGINT NOT NULL,
    UNIQUE_KEY CHAR   NOT NULL,
    CONSTRAINT UNIQUE_KEY_UN UNIQUE (UNIQUE_KEY)
);

CREATE TABLE BATCH_JOB_INSTANCE
(
    JOB_INSTANCE_ID BIGINT       NOT NULL PRIMARY KEY,
    VERSION         BIGINT       NULL,
    JOB_NAME        VARCHAR(100) NOT NULL,
    JOB_KEY         VARCHAR(32)  NOT NULL,
    CONSTRAINT JOB_INST_UN UNIQUE (JOB_NAME, JOB_KEY)
);

CREATE TABLE BATCH_JOB_EXECUTION
(
    JOB_EXECUTION_ID           BIGINT        NOT NULL PRIMARY KEY,
    VERSION                    BIGINT        NULL,
    JOB_INSTANCE_ID            BIGINT        NOT NULL,
    CREATE_TIME                DATETIME(6)   NOT NULL,
    START_TIME                 DATETIME(6)   NULL,
    END_TIME                   DATETIME(6)   NULL,
    STATUS                     VARCHAR(10)   NULL,
    EXIT_CODE                  VARCHAR(2500) NULL,
    EXIT_MESSAGE               VARCHAR(2500) NULL,
    LAST_UPDATED               DATETIME(6)   NULL,
    JOB_CONFIGURATION_LOCATION VARCHAR(2500) NULL,
    CONSTRAINT JOB_INST_EXEC_FK FOREIGN key (JOB_INSTANCE_ID) REFERENCES BATCH_JOB_INSTANCE (JOB_INSTANCE_ID)
);

CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT
(
    JOB_EXECUTION_ID   BIGINT        NOT NULL PRIMARY KEY,
    SHORT_CONTEXT      VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT text          NULL,
    CONSTRAINT JOB_EXEC_CTX_FK FOREIGN key (JOB_EXECUTION_ID) REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
);

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS
(
    JOB_EXECUTION_ID BIGINT       NOT NULL,
    TYPE_CD          VARCHAR(6)   NOT NULL,
    KEY_NAME         VARCHAR(100) NOT NULL,
    STRING_VAL       VARCHAR(250) NULL,
    DATE_VAL         DATETIME(6)  NULL,
    LONG_VAL         BIGINT       NULL,
    DOUBLE_VAL       DOUBLE       NULL,
    IDENTIFYING      CHAR         NOT NULL,
    CONSTRAINT JOB_EXEC_PARAMS_FK FOREIGN key (JOB_EXECUTION_ID) REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
);

CREATE TABLE BATCH_JOB_SEQ
(
    ID         BIGINT NOT NULL,
    UNIQUE_KEY CHAR   NOT NULL,
    CONSTRAINT UNIQUE_KEY_UN UNIQUE (UNIQUE_KEY)
);

CREATE TABLE BATCH_STEP_EXECUTION
(
    STEP_EXECUTION_ID  BIGINT        NOT NULL PRIMARY KEY,
    VERSION            BIGINT        NOT NULL,
    STEP_NAME          VARCHAR(100)  NOT NULL,
    JOB_EXECUTION_ID   BIGINT        NOT NULL,
    START_TIME         DATETIME(6)   NOT NULL,
    END_TIME           DATETIME(6)   NULL,
    STATUS             VARCHAR(10)   NULL,
    COMMIT_COUNT       BIGINT        NULL,
    READ_COUNT         BIGINT        NULL,
    FILTER_COUNT       BIGINT        NULL,
    WRITE_COUNT        BIGINT        NULL,
    READ_SKIP_COUNT    BIGINT        NULL,
    WRITE_SKIP_COUNT   BIGINT        NULL,
    PROCESS_SKIP_COUNT BIGINT        NULL,
    ROLLBACK_COUNT     BIGINT        NULL,
    EXIT_CODE          VARCHAR(2500) NULL,
    EXIT_MESSAGE       VARCHAR(2500) NULL,
    LAST_UPDATED       DATETIME(6)   NULL,
    CONSTRAINT JOB_EXEC_STEP_FK FOREIGN key (JOB_EXECUTION_ID) REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
);

CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT
(
    STEP_EXECUTION_ID  BIGINT        NOT NULL PRIMARY KEY,
    SHORT_CONTEXT      VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT text          NULL,
    CONSTRAINT STEP_EXEC_CTX_FK FOREIGN key (STEP_EXECUTION_ID) REFERENCES BATCH_STEP_EXECUTION (STEP_EXECUTION_ID)
);

CREATE TABLE BATCH_STEP_EXECUTION_SEQ
(
    ID         BIGINT NOT NULL,
    UNIQUE_KEY CHAR   NOT NULL,
    CONSTRAINT UNIQUE_KEY_UN UNIQUE (UNIQUE_KEY)
);
