spring:
  config:
    import: "classpath:/application-webtoon-core.yml"
  profiles:
    group:
      local: "webtoon-core-local"
      beta: "webtoon-core-beta"
  batch:
    initialize-schema: never
    job:
      names: ${job.name:NONE}
  main:
    web-application-type: none


---
spring:
  config:
    activate.on-profile: local

  batch:
    initialize-schema: always
