GET {{webtoonApi}}
Content-Type: application/json

###

POST {{webtoonApi}}/api/v1/login
Content-Type: application/json

{
    "loginToken": "testToken"
}

###
GET {{webtoonApi}}/api/v1/webtoons/detail?id=1
Content-Type: application/json
Authorization: Bearer testToken
