spring:
  config:
    import: "classpath:/application-webtoon-core.yml"
  profiles:
    group:
      local: "webtoon-core-local"
      beta: "webtoon-core-beta"

webtoon:
  admin:
    jwt-signing-key: p@55w0rd

---
spring:
  config:
    activate.on-profile: local

server.port: 8081

---
spring:
  config:
    activate.on-profile: beta

server.port: 8081

webtoon:
  admin:
    jwt-signing-key: ${WEBTOON_ADMIN_SIGNING_KEY}

logging:
  config: classpath:logback-beta.xml

