spring:
  config:
    import: classpath:/application-webtoon-core.yml
  profiles:
    group:
      integration-test: "webtoon-integration-test"
    active: integration-test

---
spring:
  config:
    activate:
      on-profile: integration-test

