name: run webtoon batch
on:
  push:
    branches:
      - 'not_available'
jobs:

  build:
    name: run sampleJob batch
    runs-on: [ self-hosted, linux, X64 ]
    steps:
      - run: |
          sudo java -jar -Dspring.profiles.active=beta /app/webtoon-batch/webtoon-batch.jar --job.name=sampleJob
