name: run webtoon batch
on:
  push:
    branches:
      - batch_test
jobs:

  build:
    name: run sampleJob batch
    runs-on: [ self-hosted, linux, X64 ]
    steps:
      - shell: bash
        env:
          WEBTOON_SERVICE_DB_USERNAME: ${{ secrets.WEBTOON_SERVICE_DB_USERNAME }}
          WEBTOON_SERVICE_DB_PASSWORD: ${{ secrets.WEBTOON_SERVICE_DB_PASSWORD }}
        run: |
          java -jar -Dspring.profiles.active=beta /app/webtoon-batch/webtoon-batch.jar --job.name=sampleJob
